// Code generated by ogen, DO NOT EDIT.

package client

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [3]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/v1/"
			origElem := elem
			if l := len("/v1/"); len(elem) >= l && elem[0:l] == "/v1/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "auth/"
				origElem := elem
				if l := len("auth/"); len(elem) >= l && elem[0:l] == "auth/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'a': // Prefix: "api-tokens"
					origElem := elem
					if l := len("api-tokens"); len(elem) >= l && elem[0:l] == "api-tokens" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleListAPITokensRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"
						origElem := elem
						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "tokenName"
						// Leaf parameter
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "DELETE":
								s.handleRevokeAPITokenRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "POST":
								s.handleCreateAPITokenRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "DELETE,POST")
							}

							return
						}

						elem = origElem
					}

					elem = origElem
				case 'v': // Prefix: "validate"
					origElem := elem
					if l := len("validate"); len(elem) >= l && elem[0:l] == "validate" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleValidateAPITokenRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}

					elem = origElem
				}

				elem = origElem
			case 'l': // Prefix: "locations"
				origElem := elem
				if l := len("locations"); len(elem) >= l && elem[0:l] == "locations" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleListLocationsRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET")
					}

					return
				}

				elem = origElem
			case 'o': // Prefix: "organizations"
				origElem := elem
				if l := len("organizations"); len(elem) >= l && elem[0:l] == "organizations" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListOrganizationsRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET")
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"
					origElem := elem
					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "organizationSlug"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleGetOrganizationRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PATCH":
							s.handleUpdateOrganizationRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET,PATCH")
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"
						origElem := elem
						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "audit-logs"
							origElem := elem
							if l := len("audit-logs"); len(elem) >= l && elem[0:l] == "audit-logs" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleListOrganizationAuditLogsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

							elem = origElem
						case 'd': // Prefix: "databases"
							origElem := elem
							if l := len("databases"); len(elem) >= l && elem[0:l] == "databases" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleListDatabasesRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "POST":
									s.handleCreateDatabaseRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET,POST")
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"
								origElem := elem
								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'd': // Prefix: "dumps"
									origElem := elem
									if l := len("dumps"); len(elem) >= l && elem[0:l] == "dumps" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleUploadDatabaseDumpRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, "POST")
										}

										return
									}

									elem = origElem
								}
								// Param: "databaseName"
								// Match until "/"
								idx := strings.IndexByte(elem, '/')
								if idx < 0 {
									idx = len(elem)
								}
								args[1] = elem[:idx]
								elem = elem[idx:]

								if len(elem) == 0 {
									switch r.Method {
									case "DELETE":
										s.handleDeleteDatabaseRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									case "GET":
										s.handleGetDatabaseRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "DELETE,GET")
									}

									return
								}
								switch elem[0] {
								case '/': // Prefix: "/"
									origElem := elem
									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'a': // Prefix: "auth/"
										origElem := elem
										if l := len("auth/"); len(elem) >= l && elem[0:l] == "auth/" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											break
										}
										switch elem[0] {
										case 'r': // Prefix: "rotate"
											origElem := elem
											if l := len("rotate"); len(elem) >= l && elem[0:l] == "rotate" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch r.Method {
												case "POST":
													s.handleInvalidateDatabaseTokensRequest([2]string{
														args[0],
														args[1],
													}, elemIsEscaped, w, r)
												default:
													s.notAllowed(w, r, "POST")
												}

												return
											}

											elem = origElem
										case 't': // Prefix: "tokens"
											origElem := elem
											if l := len("tokens"); len(elem) >= l && elem[0:l] == "tokens" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch r.Method {
												case "POST":
													s.handleCreateDatabaseTokenRequest([2]string{
														args[0],
														args[1],
													}, elemIsEscaped, w, r)
												default:
													s.notAllowed(w, r, "POST")
												}

												return
											}

											elem = origElem
										}

										elem = origElem
									case 'c': // Prefix: "configuration"
										origElem := elem
										if l := len("configuration"); len(elem) >= l && elem[0:l] == "configuration" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "GET":
												s.handleGetDatabaseConfigurationRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											case "PATCH":
												s.handleUpdateDatabaseConfigurationRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, "GET,PATCH")
											}

											return
										}

										elem = origElem
									case 'i': // Prefix: "instances"
										origElem := elem
										if l := len("instances"); len(elem) >= l && elem[0:l] == "instances" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											switch r.Method {
											case "GET":
												s.handleListDatabaseInstancesRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, "GET")
											}

											return
										}
										switch elem[0] {
										case '/': // Prefix: "/"
											origElem := elem
											if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
												elem = elem[l:]
											} else {
												break
											}

											// Param: "instanceName"
											// Leaf parameter
											args[2] = elem
											elem = ""

											if len(elem) == 0 {
												// Leaf node.
												switch r.Method {
												case "GET":
													s.handleGetDatabaseInstanceRequest([3]string{
														args[0],
														args[1],
														args[2],
													}, elemIsEscaped, w, r)
												default:
													s.notAllowed(w, r, "GET")
												}

												return
											}

											elem = origElem
										}

										elem = origElem
									case 's': // Prefix: "stats"
										origElem := elem
										if l := len("stats"); len(elem) >= l && elem[0:l] == "stats" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "GET":
												s.handleGetDatabaseStatsRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, "GET")
											}

											return
										}

										elem = origElem
									case 'u': // Prefix: "usage"
										origElem := elem
										if l := len("usage"); len(elem) >= l && elem[0:l] == "usage" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "GET":
												s.handleGetDatabaseUsageRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, "GET")
											}

											return
										}

										elem = origElem
									}

									elem = origElem
								}

								elem = origElem
							}

							elem = origElem
						case 'g': // Prefix: "groups"
							origElem := elem
							if l := len("groups"); len(elem) >= l && elem[0:l] == "groups" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleListGroupsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "POST":
									s.handleCreateGroupRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET,POST")
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"
								origElem := elem
								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "groupName"
								// Match until "/"
								idx := strings.IndexByte(elem, '/')
								if idx < 0 {
									idx = len(elem)
								}
								args[1] = elem[:idx]
								elem = elem[idx:]

								if len(elem) == 0 {
									switch r.Method {
									case "DELETE":
										s.handleDeleteGroupRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									case "GET":
										s.handleGetGroupRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "DELETE,GET")
									}

									return
								}
								switch elem[0] {
								case '/': // Prefix: "/"
									origElem := elem
									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'a': // Prefix: "auth/"
										origElem := elem
										if l := len("auth/"); len(elem) >= l && elem[0:l] == "auth/" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											break
										}
										switch elem[0] {
										case 'r': // Prefix: "rotate"
											origElem := elem
											if l := len("rotate"); len(elem) >= l && elem[0:l] == "rotate" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch r.Method {
												case "POST":
													s.handleInvalidateGroupTokensRequest([2]string{
														args[0],
														args[1],
													}, elemIsEscaped, w, r)
												default:
													s.notAllowed(w, r, "POST")
												}

												return
											}

											elem = origElem
										case 't': // Prefix: "tokens"
											origElem := elem
											if l := len("tokens"); len(elem) >= l && elem[0:l] == "tokens" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch r.Method {
												case "POST":
													s.handleCreateGroupTokenRequest([2]string{
														args[0],
														args[1],
													}, elemIsEscaped, w, r)
												default:
													s.notAllowed(w, r, "POST")
												}

												return
											}

											elem = origElem
										}

										elem = origElem
									case 'l': // Prefix: "locations/"
										origElem := elem
										if l := len("locations/"); len(elem) >= l && elem[0:l] == "locations/" {
											elem = elem[l:]
										} else {
											break
										}

										// Param: "location"
										// Leaf parameter
										args[2] = elem
										elem = ""

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "DELETE":
												s.handleRemoveLocationFromGroupRequest([3]string{
													args[0],
													args[1],
													args[2],
												}, elemIsEscaped, w, r)
											case "POST":
												s.handleAddLocationToGroupRequest([3]string{
													args[0],
													args[1],
													args[2],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, "DELETE,POST")
											}

											return
										}

										elem = origElem
									case 't': // Prefix: "transfer"
										origElem := elem
										if l := len("transfer"); len(elem) >= l && elem[0:l] == "transfer" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "POST":
												s.handleTransferGroupRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, "POST")
											}

											return
										}

										elem = origElem
									case 'u': // Prefix: "u"
										origElem := elem
										if l := len("u"); len(elem) >= l && elem[0:l] == "u" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											break
										}
										switch elem[0] {
										case 'n': // Prefix: "narchive"
											origElem := elem
											if l := len("narchive"); len(elem) >= l && elem[0:l] == "narchive" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch r.Method {
												case "POST":
													s.handleUnarchiveGroupRequest([2]string{
														args[0],
														args[1],
													}, elemIsEscaped, w, r)
												default:
													s.notAllowed(w, r, "POST")
												}

												return
											}

											elem = origElem
										case 'p': // Prefix: "pdate"
											origElem := elem
											if l := len("pdate"); len(elem) >= l && elem[0:l] == "pdate" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch r.Method {
												case "POST":
													s.handleUpdateGroupDatabasesRequest([2]string{
														args[0],
														args[1],
													}, elemIsEscaped, w, r)
												default:
													s.notAllowed(w, r, "POST")
												}

												return
											}

											elem = origElem
										}

										elem = origElem
									}

									elem = origElem
								}

								elem = origElem
							}

							elem = origElem
						case 'i': // Prefix: "inv"
							origElem := elem
							if l := len("inv"); len(elem) >= l && elem[0:l] == "inv" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'i': // Prefix: "ites"
								origElem := elem
								if l := len("ites"); len(elem) >= l && elem[0:l] == "ites" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch r.Method {
									case "GET":
										s.handleListOrganizationInvitesRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									case "POST":
										s.handleInviteOrganizationMemberRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "GET,POST")
									}

									return
								}
								switch elem[0] {
								case '/': // Prefix: "/"
									origElem := elem
									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "email"
									// Leaf parameter
									args[1] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "DELETE":
											s.handleDeleteOrganizationInviteByEmailRequest([2]string{
												args[0],
												args[1],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, "DELETE")
										}

										return
									}

									elem = origElem
								}

								elem = origElem
							case 'o': // Prefix: "oices"
								origElem := elem
								if l := len("oices"); len(elem) >= l && elem[0:l] == "oices" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleListOrganizationInvoicesRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "GET")
									}

									return
								}

								elem = origElem
							}

							elem = origElem
						case 'm': // Prefix: "members"
							origElem := elem
							if l := len("members"); len(elem) >= l && elem[0:l] == "members" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleListOrganizationMembersRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "POST":
									s.handleAddOrganizationMemberRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET,POST")
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"
								origElem := elem
								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "username"
								// Leaf parameter
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "DELETE":
										s.handleRemoveOrganizationMemberRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									case "GET":
										s.handleGetOrganizationMemberRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									case "PATCH":
										s.handleUpdateMemberRoleRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "DELETE,GET,PATCH")
									}

									return
								}

								elem = origElem
							}

							elem = origElem
						case 'p': // Prefix: "plans"
							origElem := elem
							if l := len("plans"); len(elem) >= l && elem[0:l] == "plans" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleListOrganizationPlansRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

							elem = origElem
						case 's': // Prefix: "subscription"
							origElem := elem
							if l := len("subscription"); len(elem) >= l && elem[0:l] == "subscription" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetOrganizationSubscriptionRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

							elem = origElem
						case 'u': // Prefix: "usage"
							origElem := elem
							if l := len("usage"); len(elem) >= l && elem[0:l] == "usage" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetOrganizationUsageRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

							elem = origElem
						}

						elem = origElem
					}

					elem = origElem
				}

				elem = origElem
			}

			elem = origElem
		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name        string
	summary     string
	operationID string
	pathPattern string
	count       int
	args        [3]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/v1/"
			origElem := elem
			if l := len("/v1/"); len(elem) >= l && elem[0:l] == "/v1/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "auth/"
				origElem := elem
				if l := len("auth/"); len(elem) >= l && elem[0:l] == "auth/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'a': // Prefix: "api-tokens"
					origElem := elem
					if l := len("api-tokens"); len(elem) >= l && elem[0:l] == "api-tokens" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = ListAPITokensOperation
							r.summary = "List API Tokens"
							r.operationID = "listAPITokens"
							r.pathPattern = "/v1/auth/api-tokens"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"
						origElem := elem
						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "tokenName"
						// Leaf parameter
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "DELETE":
								r.name = RevokeAPITokenOperation
								r.summary = "Revoke API Token"
								r.operationID = "revokeAPIToken"
								r.pathPattern = "/v1/auth/api-tokens/{tokenName}"
								r.args = args
								r.count = 1
								return r, true
							case "POST":
								r.name = CreateAPITokenOperation
								r.summary = "Create API Token"
								r.operationID = "createAPIToken"
								r.pathPattern = "/v1/auth/api-tokens/{tokenName}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

						elem = origElem
					}

					elem = origElem
				case 'v': // Prefix: "validate"
					origElem := elem
					if l := len("validate"); len(elem) >= l && elem[0:l] == "validate" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = ValidateAPITokenOperation
							r.summary = "Validate API Token"
							r.operationID = "validateAPIToken"
							r.pathPattern = "/v1/auth/validate"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

					elem = origElem
				}

				elem = origElem
			case 'l': // Prefix: "locations"
				origElem := elem
				if l := len("locations"); len(elem) >= l && elem[0:l] == "locations" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = ListLocationsOperation
						r.summary = "List Locations"
						r.operationID = "listLocations"
						r.pathPattern = "/v1/locations"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

				elem = origElem
			case 'o': // Prefix: "organizations"
				origElem := elem
				if l := len("organizations"); len(elem) >= l && elem[0:l] == "organizations" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListOrganizationsOperation
						r.summary = "List Organizations"
						r.operationID = "listOrganizations"
						r.pathPattern = "/v1/organizations"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"
					origElem := elem
					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "organizationSlug"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = GetOrganizationOperation
							r.summary = "Retrieve Organization"
							r.operationID = "getOrganization"
							r.pathPattern = "/v1/organizations/{organizationSlug}"
							r.args = args
							r.count = 1
							return r, true
						case "PATCH":
							r.name = UpdateOrganizationOperation
							r.summary = "Update Organization"
							r.operationID = "updateOrganization"
							r.pathPattern = "/v1/organizations/{organizationSlug}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"
						origElem := elem
						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "audit-logs"
							origElem := elem
							if l := len("audit-logs"); len(elem) >= l && elem[0:l] == "audit-logs" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = ListOrganizationAuditLogsOperation
									r.summary = "List Audit Logs"
									r.operationID = "listOrganizationAuditLogs"
									r.pathPattern = "/v1/organizations/{organizationSlug}/audit-logs"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

							elem = origElem
						case 'd': // Prefix: "databases"
							origElem := elem
							if l := len("databases"); len(elem) >= l && elem[0:l] == "databases" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = ListDatabasesOperation
									r.summary = "List Databases"
									r.operationID = "listDatabases"
									r.pathPattern = "/v1/organizations/{organizationSlug}/databases"
									r.args = args
									r.count = 1
									return r, true
								case "POST":
									r.name = CreateDatabaseOperation
									r.summary = "Create Database"
									r.operationID = "createDatabase"
									r.pathPattern = "/v1/organizations/{organizationSlug}/databases"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"
								origElem := elem
								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'd': // Prefix: "dumps"
									origElem := elem
									if l := len("dumps"); len(elem) >= l && elem[0:l] == "dumps" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = UploadDatabaseDumpOperation
											r.summary = "Upload SQLite Dump"
											r.operationID = "uploadDatabaseDump"
											r.pathPattern = "/v1/organizations/{organizationSlug}/databases/dumps"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}

									elem = origElem
								}
								// Param: "databaseName"
								// Match until "/"
								idx := strings.IndexByte(elem, '/')
								if idx < 0 {
									idx = len(elem)
								}
								args[1] = elem[:idx]
								elem = elem[idx:]

								if len(elem) == 0 {
									switch method {
									case "DELETE":
										r.name = DeleteDatabaseOperation
										r.summary = "Delete Database"
										r.operationID = "deleteDatabase"
										r.pathPattern = "/v1/organizations/{organizationSlug}/databases/{databaseName}"
										r.args = args
										r.count = 2
										return r, true
									case "GET":
										r.name = GetDatabaseOperation
										r.summary = "Retrieve Database"
										r.operationID = "getDatabase"
										r.pathPattern = "/v1/organizations/{organizationSlug}/databases/{databaseName}"
										r.args = args
										r.count = 2
										return r, true
									default:
										return
									}
								}
								switch elem[0] {
								case '/': // Prefix: "/"
									origElem := elem
									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'a': // Prefix: "auth/"
										origElem := elem
										if l := len("auth/"); len(elem) >= l && elem[0:l] == "auth/" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											break
										}
										switch elem[0] {
										case 'r': // Prefix: "rotate"
											origElem := elem
											if l := len("rotate"); len(elem) >= l && elem[0:l] == "rotate" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch method {
												case "POST":
													r.name = InvalidateDatabaseTokensOperation
													r.summary = "Invalidate All Database Auth Tokens"
													r.operationID = "invalidateDatabaseTokens"
													r.pathPattern = "/v1/organizations/{organizationSlug}/databases/{databaseName}/auth/rotate"
													r.args = args
													r.count = 2
													return r, true
												default:
													return
												}
											}

											elem = origElem
										case 't': // Prefix: "tokens"
											origElem := elem
											if l := len("tokens"); len(elem) >= l && elem[0:l] == "tokens" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch method {
												case "POST":
													r.name = CreateDatabaseTokenOperation
													r.summary = "Generate Database Auth Token"
													r.operationID = "createDatabaseToken"
													r.pathPattern = "/v1/organizations/{organizationSlug}/databases/{databaseName}/auth/tokens"
													r.args = args
													r.count = 2
													return r, true
												default:
													return
												}
											}

											elem = origElem
										}

										elem = origElem
									case 'c': // Prefix: "configuration"
										origElem := elem
										if l := len("configuration"); len(elem) >= l && elem[0:l] == "configuration" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "GET":
												r.name = GetDatabaseConfigurationOperation
												r.summary = "Retrieve Database Configuration"
												r.operationID = "getDatabaseConfiguration"
												r.pathPattern = "/v1/organizations/{organizationSlug}/databases/{databaseName}/configuration"
												r.args = args
												r.count = 2
												return r, true
											case "PATCH":
												r.name = UpdateDatabaseConfigurationOperation
												r.summary = "Update Database Configuration"
												r.operationID = "updateDatabaseConfiguration"
												r.pathPattern = "/v1/organizations/{organizationSlug}/databases/{databaseName}/configuration"
												r.args = args
												r.count = 2
												return r, true
											default:
												return
											}
										}

										elem = origElem
									case 'i': // Prefix: "instances"
										origElem := elem
										if l := len("instances"); len(elem) >= l && elem[0:l] == "instances" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											switch method {
											case "GET":
												r.name = ListDatabaseInstancesOperation
												r.summary = "List Database Instances"
												r.operationID = "listDatabaseInstances"
												r.pathPattern = "/v1/organizations/{organizationSlug}/databases/{databaseName}/instances"
												r.args = args
												r.count = 2
												return r, true
											default:
												return
											}
										}
										switch elem[0] {
										case '/': // Prefix: "/"
											origElem := elem
											if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
												elem = elem[l:]
											} else {
												break
											}

											// Param: "instanceName"
											// Leaf parameter
											args[2] = elem
											elem = ""

											if len(elem) == 0 {
												// Leaf node.
												switch method {
												case "GET":
													r.name = GetDatabaseInstanceOperation
													r.summary = "Retrieve Database Instance"
													r.operationID = "getDatabaseInstance"
													r.pathPattern = "/v1/organizations/{organizationSlug}/databases/{databaseName}/instances/{instanceName}"
													r.args = args
													r.count = 3
													return r, true
												default:
													return
												}
											}

											elem = origElem
										}

										elem = origElem
									case 's': // Prefix: "stats"
										origElem := elem
										if l := len("stats"); len(elem) >= l && elem[0:l] == "stats" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "GET":
												r.name = GetDatabaseStatsOperation
												r.summary = "Retrieve Database Stats"
												r.operationID = "getDatabaseStats"
												r.pathPattern = "/v1/organizations/{organizationSlug}/databases/{databaseName}/stats"
												r.args = args
												r.count = 2
												return r, true
											default:
												return
											}
										}

										elem = origElem
									case 'u': // Prefix: "usage"
										origElem := elem
										if l := len("usage"); len(elem) >= l && elem[0:l] == "usage" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "GET":
												r.name = GetDatabaseUsageOperation
												r.summary = "Retrieve Database Usage"
												r.operationID = "getDatabaseUsage"
												r.pathPattern = "/v1/organizations/{organizationSlug}/databases/{databaseName}/usage"
												r.args = args
												r.count = 2
												return r, true
											default:
												return
											}
										}

										elem = origElem
									}

									elem = origElem
								}

								elem = origElem
							}

							elem = origElem
						case 'g': // Prefix: "groups"
							origElem := elem
							if l := len("groups"); len(elem) >= l && elem[0:l] == "groups" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = ListGroupsOperation
									r.summary = "List Groups"
									r.operationID = "listGroups"
									r.pathPattern = "/v1/organizations/{organizationSlug}/groups"
									r.args = args
									r.count = 1
									return r, true
								case "POST":
									r.name = CreateGroupOperation
									r.summary = "Create Group"
									r.operationID = "createGroup"
									r.pathPattern = "/v1/organizations/{organizationSlug}/groups"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"
								origElem := elem
								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "groupName"
								// Match until "/"
								idx := strings.IndexByte(elem, '/')
								if idx < 0 {
									idx = len(elem)
								}
								args[1] = elem[:idx]
								elem = elem[idx:]

								if len(elem) == 0 {
									switch method {
									case "DELETE":
										r.name = DeleteGroupOperation
										r.summary = "Delete Group"
										r.operationID = "deleteGroup"
										r.pathPattern = "/v1/organizations/{organizationSlug}/groups/{groupName}"
										r.args = args
										r.count = 2
										return r, true
									case "GET":
										r.name = GetGroupOperation
										r.summary = "Retrieve Group"
										r.operationID = "getGroup"
										r.pathPattern = "/v1/organizations/{organizationSlug}/groups/{groupName}"
										r.args = args
										r.count = 2
										return r, true
									default:
										return
									}
								}
								switch elem[0] {
								case '/': // Prefix: "/"
									origElem := elem
									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'a': // Prefix: "auth/"
										origElem := elem
										if l := len("auth/"); len(elem) >= l && elem[0:l] == "auth/" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											break
										}
										switch elem[0] {
										case 'r': // Prefix: "rotate"
											origElem := elem
											if l := len("rotate"); len(elem) >= l && elem[0:l] == "rotate" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch method {
												case "POST":
													r.name = InvalidateGroupTokensOperation
													r.summary = "Invalidate All Group Auth Tokens"
													r.operationID = "invalidateGroupTokens"
													r.pathPattern = "/v1/organizations/{organizationSlug}/groups/{groupName}/auth/rotate"
													r.args = args
													r.count = 2
													return r, true
												default:
													return
												}
											}

											elem = origElem
										case 't': // Prefix: "tokens"
											origElem := elem
											if l := len("tokens"); len(elem) >= l && elem[0:l] == "tokens" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch method {
												case "POST":
													r.name = CreateGroupTokenOperation
													r.summary = "Create Group Auth Token"
													r.operationID = "createGroupToken"
													r.pathPattern = "/v1/organizations/{organizationSlug}/groups/{groupName}/auth/tokens"
													r.args = args
													r.count = 2
													return r, true
												default:
													return
												}
											}

											elem = origElem
										}

										elem = origElem
									case 'l': // Prefix: "locations/"
										origElem := elem
										if l := len("locations/"); len(elem) >= l && elem[0:l] == "locations/" {
											elem = elem[l:]
										} else {
											break
										}

										// Param: "location"
										// Leaf parameter
										args[2] = elem
										elem = ""

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "DELETE":
												r.name = RemoveLocationFromGroupOperation
												r.summary = "Remove Location from Group"
												r.operationID = "removeLocationFromGroup"
												r.pathPattern = "/v1/organizations/{organizationSlug}/groups/{groupName}/locations/{location}"
												r.args = args
												r.count = 3
												return r, true
											case "POST":
												r.name = AddLocationToGroupOperation
												r.summary = "Add Location to Group"
												r.operationID = "addLocationToGroup"
												r.pathPattern = "/v1/organizations/{organizationSlug}/groups/{groupName}/locations/{location}"
												r.args = args
												r.count = 3
												return r, true
											default:
												return
											}
										}

										elem = origElem
									case 't': // Prefix: "transfer"
										origElem := elem
										if l := len("transfer"); len(elem) >= l && elem[0:l] == "transfer" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "POST":
												r.name = TransferGroupOperation
												r.summary = "Transfer Group"
												r.operationID = "transferGroup"
												r.pathPattern = "/v1/organizations/{organizationSlug}/groups/{groupName}/transfer"
												r.args = args
												r.count = 2
												return r, true
											default:
												return
											}
										}

										elem = origElem
									case 'u': // Prefix: "u"
										origElem := elem
										if l := len("u"); len(elem) >= l && elem[0:l] == "u" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											break
										}
										switch elem[0] {
										case 'n': // Prefix: "narchive"
											origElem := elem
											if l := len("narchive"); len(elem) >= l && elem[0:l] == "narchive" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch method {
												case "POST":
													r.name = UnarchiveGroupOperation
													r.summary = "Unarchive Group"
													r.operationID = "unarchiveGroup"
													r.pathPattern = "/v1/organizations/{organizationSlug}/groups/{groupName}/unarchive"
													r.args = args
													r.count = 2
													return r, true
												default:
													return
												}
											}

											elem = origElem
										case 'p': // Prefix: "pdate"
											origElem := elem
											if l := len("pdate"); len(elem) >= l && elem[0:l] == "pdate" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch method {
												case "POST":
													r.name = UpdateGroupDatabasesOperation
													r.summary = "Update Databases in a Group"
													r.operationID = "updateGroupDatabases"
													r.pathPattern = "/v1/organizations/{organizationSlug}/groups/{groupName}/update"
													r.args = args
													r.count = 2
													return r, true
												default:
													return
												}
											}

											elem = origElem
										}

										elem = origElem
									}

									elem = origElem
								}

								elem = origElem
							}

							elem = origElem
						case 'i': // Prefix: "inv"
							origElem := elem
							if l := len("inv"); len(elem) >= l && elem[0:l] == "inv" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'i': // Prefix: "ites"
								origElem := elem
								if l := len("ites"); len(elem) >= l && elem[0:l] == "ites" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch method {
									case "GET":
										r.name = ListOrganizationInvitesOperation
										r.summary = "List Invites"
										r.operationID = "listOrganizationInvites"
										r.pathPattern = "/v1/organizations/{organizationSlug}/invites"
										r.args = args
										r.count = 1
										return r, true
									case "POST":
										r.name = InviteOrganizationMemberOperation
										r.summary = "Invite Organization Member"
										r.operationID = "inviteOrganizationMember"
										r.pathPattern = "/v1/organizations/{organizationSlug}/invites"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}
								switch elem[0] {
								case '/': // Prefix: "/"
									origElem := elem
									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "email"
									// Leaf parameter
									args[1] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "DELETE":
											r.name = DeleteOrganizationInviteByEmailOperation
											r.summary = "Delete Invite"
											r.operationID = "deleteOrganizationInviteByEmail"
											r.pathPattern = "/v1/organizations/{organizationSlug}/invites/{email}"
											r.args = args
											r.count = 2
											return r, true
										default:
											return
										}
									}

									elem = origElem
								}

								elem = origElem
							case 'o': // Prefix: "oices"
								origElem := elem
								if l := len("oices"); len(elem) >= l && elem[0:l] == "oices" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = ListOrganizationInvoicesOperation
										r.summary = "List Invoices"
										r.operationID = "listOrganizationInvoices"
										r.pathPattern = "/v1/organizations/{organizationSlug}/invoices"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

								elem = origElem
							}

							elem = origElem
						case 'm': // Prefix: "members"
							origElem := elem
							if l := len("members"); len(elem) >= l && elem[0:l] == "members" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = ListOrganizationMembersOperation
									r.summary = "List Members"
									r.operationID = "listOrganizationMembers"
									r.pathPattern = "/v1/organizations/{organizationSlug}/members"
									r.args = args
									r.count = 1
									return r, true
								case "POST":
									r.name = AddOrganizationMemberOperation
									r.summary = "Add Member"
									r.operationID = "addOrganizationMember"
									r.pathPattern = "/v1/organizations/{organizationSlug}/members"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"
								origElem := elem
								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "username"
								// Leaf parameter
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "DELETE":
										r.name = RemoveOrganizationMemberOperation
										r.summary = "Remove Member"
										r.operationID = "removeOrganizationMember"
										r.pathPattern = "/v1/organizations/{organizationSlug}/members/{username}"
										r.args = args
										r.count = 2
										return r, true
									case "GET":
										r.name = GetOrganizationMemberOperation
										r.summary = "Retrieve Member"
										r.operationID = "getOrganizationMember"
										r.pathPattern = "/v1/organizations/{organizationSlug}/members/{username}"
										r.args = args
										r.count = 2
										return r, true
									case "PATCH":
										r.name = UpdateMemberRoleOperation
										r.summary = "Update Member Role"
										r.operationID = "updateMemberRole"
										r.pathPattern = "/v1/organizations/{organizationSlug}/members/{username}"
										r.args = args
										r.count = 2
										return r, true
									default:
										return
									}
								}

								elem = origElem
							}

							elem = origElem
						case 'p': // Prefix: "plans"
							origElem := elem
							if l := len("plans"); len(elem) >= l && elem[0:l] == "plans" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = ListOrganizationPlansOperation
									r.summary = "List Plans"
									r.operationID = "listOrganizationPlans"
									r.pathPattern = "/v1/organizations/{organizationSlug}/plans"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

							elem = origElem
						case 's': // Prefix: "subscription"
							origElem := elem
							if l := len("subscription"); len(elem) >= l && elem[0:l] == "subscription" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetOrganizationSubscriptionOperation
									r.summary = "Current Subscription"
									r.operationID = "getOrganizationSubscription"
									r.pathPattern = "/v1/organizations/{organizationSlug}/subscription"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

							elem = origElem
						case 'u': // Prefix: "usage"
							origElem := elem
							if l := len("usage"); len(elem) >= l && elem[0:l] == "usage" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetOrganizationUsageOperation
									r.summary = "Organization Usage"
									r.operationID = "getOrganizationUsage"
									r.pathPattern = "/v1/organizations/{organizationSlug}/usage"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

							elem = origElem
						}

						elem = origElem
					}

					elem = origElem
				}

				elem = origElem
			}

			elem = origElem
		}
	}
	return r, false
}
