// Code generated by ogen, DO NOT EDIT.
package client

type AddLocationToGroupRes interface {
	addLocationToGroupRes()
}

type AddOrganizationMemberRes interface {
	addOrganizationMemberRes()
}

type CreateDatabaseRes interface {
	createDatabaseRes()
}

type CreateDatabaseTokenRes interface {
	createDatabaseTokenRes()
}

type CreateGroupRes interface {
	createGroupRes()
}

type CreateGroupTokenRes interface {
	createGroupTokenRes()
}

type DeleteDatabaseRes interface {
	deleteDatabaseRes()
}

type DeleteGroupRes interface {
	deleteGroupRes()
}

type DeleteOrganizationInviteByEmailRes interface {
	deleteOrganizationInviteByEmailRes()
}

type GetDatabaseRes interface {
	getDatabaseRes()
}

type GetDatabaseStatsRes interface {
	getDatabaseStatsRes()
}

type GetDatabaseUsageRes interface {
	getDatabaseUsageRes()
}

type GetGroupRes interface {
	getGroupRes()
}

type GetOrganizationMemberRes interface {
	getOrganizationMemberRes()
}

type GetOrganizationRes interface {
	getOrganizationRes()
}

type InvalidateDatabaseTokensRes interface {
	invalidateDatabaseTokensRes()
}

type InvalidateGroupTokensRes interface {
	invalidateGroupTokensRes()
}

type RemoveLocationFromGroupRes interface {
	removeLocationFromGroupRes()
}

type RemoveOrganizationMemberRes interface {
	removeOrganizationMemberRes()
}

type TransferGroupRes interface {
	transferGroupRes()
}

type UnarchiveGroupRes interface {
	unarchiveGroupRes()
}

type UpdateGroupDatabasesRes interface {
	updateGroupDatabasesRes()
}

type UpdateMemberRoleRes interface {
	updateMemberRoleRes()
}
