// Code generated by ogen, DO NOT EDIT.

package client

// setDefaults set default value of fields.
func (s *Database) setDefaults() {
	{
		val := string("logical")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1OrganizationsOrganizationNameInvitesPostReq) setDefaults() {
	{
		val := V1OrganizationsOrganizationNameInvitesPostReqRole("member")
		s.Role.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1OrganizationsOrganizationNameMembersPostReq) setDefaults() {
	{
		val := V1OrganizationsOrganizationNameMembersPostReqRole("member")
		s.Role.SetTo(val)
	}
}
