// Code generated by ogen, DO NOT EDIT.

package client

// setDefaults set default value of fields.
func (s *AddOrganizationMemberReq) setDefaults() {
	{
		val := AddOrganizationMemberReqRole("member")
		s.Role.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *Database) setDefaults() {
	{
		val := string("logical")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *InviteOrganizationMemberReq) setDefaults() {
	{
		val := InviteOrganizationMemberReqRole("member")
		s.Role.SetTo(val)
	}
}
